// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;

namespace MauiReactor.XamlConverterTool;
public partial class MauiCodeButton : MauiCodeView
{
    public MauiCodeButton(XElement xamlElement) : base(xamlElement)
    {
        RegisterProperty("ContentLayout", "Microsoft.Maui.Controls.Button.ButtonContentLayout", false);
        RegisterProperty("Text", "string", false);
        RegisterProperty("TextColor", "Microsoft.Maui.Graphics.Color", false);
        RegisterProperty("CharacterSpacing", "double", false);
        RegisterProperty("FontFamily", "string", false);
        RegisterProperty("FontSize", "double", false);
        RegisterProperty("TextTransform", "Microsoft.Maui.TextTransform", true);
        RegisterProperty("FontAttributes", "Microsoft.Maui.Controls.FontAttributes", true);
        RegisterProperty("FontAutoScalingEnabled", "bool", false);
        RegisterProperty("BorderWidth", "double", false);
        RegisterProperty("BorderColor", "Microsoft.Maui.Graphics.Color", false);
        RegisterProperty("CornerRadius", "int", false);
        RegisterProperty("ImageSource", "Microsoft.Maui.Controls.ImageSource", false);
        RegisterProperty("Padding", "Microsoft.Maui.Thickness", false);
        RegisterProperty("LineBreakMode", "Microsoft.Maui.LineBreakMode", true);
    }
}