// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;

namespace MauiReactor.XamlConverterTool;
public partial class MauiCodeEntry : MauiCodeInputView
{
    public MauiCodeEntry(XElement xamlElement) : base(xamlElement)
    {
        RegisterProperty("ReturnType", "Microsoft.Maui.ReturnType", true);
        RegisterProperty("IsPassword", "bool", false);
        RegisterProperty("HorizontalTextAlignment", "Microsoft.Maui.TextAlignment", true);
        RegisterProperty("VerticalTextAlignment", "Microsoft.Maui.TextAlignment", true);
        RegisterProperty("ClearButtonVisibility", "Microsoft.Maui.ClearButtonVisibility", true);
    }
}