// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;

namespace MauiReactor.XamlConverterTool;
public partial class MauiCodeFlyoutPage : MauiCodePage
{
    public MauiCodeFlyoutPage(XElement xamlElement) : base(xamlElement)
    {
        RegisterProperty("IsGestureEnabled", "bool", false);
        RegisterProperty("IsPresented", "bool", false);
        RegisterProperty("FlyoutLayoutBehavior", "Microsoft.Maui.Controls.FlyoutLayoutBehavior", true);
    }
}