// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using MauiReactor.Animations;
using MauiReactor.Shapes;
using MauiReactor.Internals;

#nullable enable
namespace MauiReactor;
public partial interface IItemsLayout : IVisualNodeWithNativeControl
{
}

public abstract partial class ItemsLayout<T> : VisualNode<T>, IItemsLayout where T : Microsoft.Maui.Controls.ItemsLayout, new()
{
    protected ItemsLayout(Action<T?>? componentRefAction = null) : base(componentRefAction)
    {
        ItemsLayoutStyles.Default?.Invoke(this);
    }

    partial void OnBeginAnimate();
    partial void OnEndAnimate();
    protected override void OnThemeChanged()
    {
        if (ThemeKey != null && ItemsLayoutStyles.Themes.TryGetValue(ThemeKey, out var styleAction))
        {
            styleAction(this);
        }

        base.OnThemeChanged();
    }

    partial void Migrated(VisualNode newNode);
    protected override void OnMigrated(VisualNode newNode)
    {
        Migrated(newNode);
        base.OnMigrated(newNode);
    }
}

public static partial class ItemsLayoutExtensions
{
    public static T SnapPointsAlignment<T>(this T itemsLayout, Microsoft.Maui.Controls.SnapPointsAlignment snapPointsAlignment)
        where T : IItemsLayout
    {
        //itemsLayout.SnapPointsAlignment = snapPointsAlignment;
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsAlignmentProperty, snapPointsAlignment);
        return itemsLayout;
    }

    public static T ItemsLayoutSnapPointsAlignment<T>(this T itemsLayout, Microsoft.Maui.Controls.SnapPointsAlignment snapPointsAlignment)
        where T : Component
    {
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsAlignmentProperty, snapPointsAlignment);
        return itemsLayout;
    }

    public static T SnapPointsAlignment<T>(this T itemsLayout, Func<Microsoft.Maui.Controls.SnapPointsAlignment> snapPointsAlignmentFunc, IComponentWithState? componentWithState = null)
        where T : IItemsLayout
    {
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsAlignmentProperty, new PropertyValue<Microsoft.Maui.Controls.SnapPointsAlignment>(snapPointsAlignmentFunc, componentWithState));
        return itemsLayout;
    }

    public static T ItemsLayoutSnapPointsAlignment<T>(this T itemsLayout, Func<Microsoft.Maui.Controls.SnapPointsAlignment> snapPointsAlignmentFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsAlignmentProperty, new PropertyValue<Microsoft.Maui.Controls.SnapPointsAlignment>(snapPointsAlignmentFunc, componentWithState));
        return itemsLayout;
    }

    public static T SnapPointsType<T>(this T itemsLayout, Microsoft.Maui.Controls.SnapPointsType snapPointsType)
        where T : IItemsLayout
    {
        //itemsLayout.SnapPointsType = snapPointsType;
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsTypeProperty, snapPointsType);
        return itemsLayout;
    }

    public static T ItemsLayoutSnapPointsType<T>(this T itemsLayout, Microsoft.Maui.Controls.SnapPointsType snapPointsType)
        where T : Component
    {
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsTypeProperty, snapPointsType);
        return itemsLayout;
    }

    public static T SnapPointsType<T>(this T itemsLayout, Func<Microsoft.Maui.Controls.SnapPointsType> snapPointsTypeFunc, IComponentWithState? componentWithState = null)
        where T : IItemsLayout
    {
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsTypeProperty, new PropertyValue<Microsoft.Maui.Controls.SnapPointsType>(snapPointsTypeFunc, componentWithState));
        return itemsLayout;
    }

    public static T ItemsLayoutSnapPointsType<T>(this T itemsLayout, Func<Microsoft.Maui.Controls.SnapPointsType> snapPointsTypeFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        itemsLayout.SetProperty(Microsoft.Maui.Controls.ItemsLayout.SnapPointsTypeProperty, new PropertyValue<Microsoft.Maui.Controls.SnapPointsType>(snapPointsTypeFunc, componentWithState));
        return itemsLayout;
    }
}

public static partial class ItemsLayoutStyles
{
    public static Action<IItemsLayout>? Default { get; set; }
    public static Dictionary<string, Action<IItemsLayout>> Themes { get; } = [];
}