// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using MauiReactor.Animations;
using MauiReactor.Shapes;
using MauiReactor.Internals;

#nullable enable
namespace MauiReactor;
public partial interface INavigableElement : IStyleableElement
{
}

public abstract partial class NavigableElement<T> : StyleableElement<T>, INavigableElement where T : Microsoft.Maui.Controls.NavigableElement, new()
{
    protected NavigableElement()
    {
        NavigableElementStyles.Default?.Invoke(this);
    }

    protected NavigableElement(Action<T?> componentRefAction) : base(componentRefAction)
    {
        NavigableElementStyles.Default?.Invoke(this);
    }

    protected override void OnUpdate()
    {
        OnBeginUpdate();
        base.OnUpdate();
        OnEndUpdate();
    }

    partial void OnBeginUpdate();
    partial void OnEndUpdate();
    partial void OnBeginAnimate();
    partial void OnEndAnimate();
    protected override void OnThemeChanged()
    {
        if (ThemeKey != null && NavigableElementStyles.Themes.TryGetValue(ThemeKey, out var styleAction))
        {
            styleAction(this);
        }

        base.OnThemeChanged();
    }

    partial void Migrated(VisualNode newNode);
    protected override void OnMigrated(VisualNode newNode)
    {
        Migrated(newNode);
        base.OnMigrated(newNode);
    }
}

public static partial class NavigableElementExtensions
{
}

public static partial class NavigableElementStyles
{
    public static Action<INavigableElement>? Default { get; set; }
    public static Dictionary<string, Action<INavigableElement>> Themes { get; } = [];
}