// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using MauiReactor.Animations;
using MauiReactor.Shapes;
using MauiReactor.Internals;

#nullable enable
namespace MauiReactor;
public partial interface ITimePicker : IView
{
    EventCommand<TimeChangedEventArgs>? TimeSelectedEvent { get; set; }

    EventCommand<TimePickerOpenedEventArgs>? OpenedEvent { get; set; }

    EventCommand<TimePickerClosedEventArgs>? ClosedEvent { get; set; }
}

public partial class TimePicker<T> : View<T>, ITimePicker where T : Microsoft.Maui.Controls.TimePicker, new()
{
    public TimePicker(Action<T?>? componentRefAction = null) : base(componentRefAction)
    {
        TimePickerStyles.Default?.Invoke(this);
    }

    EventCommand<TimeChangedEventArgs>? ITimePicker.TimeSelectedEvent { get; set; }

    EventCommand<TimePickerOpenedEventArgs>? ITimePicker.OpenedEvent { get; set; }

    EventCommand<TimePickerClosedEventArgs>? ITimePicker.ClosedEvent { get; set; }

    partial void OnBeginAnimate();
    partial void OnEndAnimate();
    protected override void OnThemeChanged()
    {
        if (ThemeKey != null && TimePickerStyles.Themes.TryGetValue(ThemeKey, out var styleAction))
        {
            styleAction(this);
        }

        base.OnThemeChanged();
    }

    partial void OnAttachingNativeEvents();
    partial void OnDetachingNativeEvents();
    private EventCommand<TimeChangedEventArgs>? _executingTimeSelectedEvent;
    private EventCommand<TimePickerOpenedEventArgs>? _executingOpenedEvent;
    private EventCommand<TimePickerClosedEventArgs>? _executingClosedEvent;
    protected override void OnAttachNativeEvents()
    {
        Validate.EnsureNotNull(NativeControl);
        var thisAsITimePicker = (ITimePicker)this;
        if (thisAsITimePicker.TimeSelectedEvent != null)
        {
            NativeControl.TimeSelected += NativeControl_TimeSelected;
        }

        if (thisAsITimePicker.OpenedEvent != null)
        {
            NativeControl.Opened += NativeControl_Opened;
        }

        if (thisAsITimePicker.ClosedEvent != null)
        {
            NativeControl.Closed += NativeControl_Closed;
        }

        OnAttachingNativeEvents();
        base.OnAttachNativeEvents();
    }

    private void NativeControl_TimeSelected(object? sender, TimeChangedEventArgs e)
    {
        var thisAsITimePicker = (ITimePicker)this;
        if (_executingTimeSelectedEvent == null || _executingTimeSelectedEvent.IsCompleted)
        {
            _executingTimeSelectedEvent = thisAsITimePicker.TimeSelectedEvent;
            _executingTimeSelectedEvent?.Execute(sender, e);
        }
    }

    private void NativeControl_Opened(object? sender, TimePickerOpenedEventArgs e)
    {
        var thisAsITimePicker = (ITimePicker)this;
        if (_executingOpenedEvent == null || _executingOpenedEvent.IsCompleted)
        {
            _executingOpenedEvent = thisAsITimePicker.OpenedEvent;
            _executingOpenedEvent?.Execute(sender, e);
        }
    }

    private void NativeControl_Closed(object? sender, TimePickerClosedEventArgs e)
    {
        var thisAsITimePicker = (ITimePicker)this;
        if (_executingClosedEvent == null || _executingClosedEvent.IsCompleted)
        {
            _executingClosedEvent = thisAsITimePicker.ClosedEvent;
            _executingClosedEvent?.Execute(sender, e);
        }
    }

    protected override void OnDetachNativeEvents()
    {
        if (NativeControl != null)
        {
            NativeControl.TimeSelected -= NativeControl_TimeSelected;
            NativeControl.Opened -= NativeControl_Opened;
            NativeControl.Closed -= NativeControl_Closed;
        }

        OnDetachingNativeEvents();
        base.OnDetachNativeEvents();
    }

    partial void Migrated(VisualNode newNode);
    protected override void OnMigrated(VisualNode newNode)
    {
        if (newNode is TimePicker<T> @timepicker)
        {
            if (_executingTimeSelectedEvent != null && !_executingTimeSelectedEvent.IsCompleted)
            {
                @timepicker._executingTimeSelectedEvent = _executingTimeSelectedEvent;
            }

            if (_executingOpenedEvent != null && !_executingOpenedEvent.IsCompleted)
            {
                @timepicker._executingOpenedEvent = _executingOpenedEvent;
            }

            if (_executingClosedEvent != null && !_executingClosedEvent.IsCompleted)
            {
                @timepicker._executingClosedEvent = _executingClosedEvent;
            }
        }

        Migrated(newNode);
        base.OnMigrated(newNode);
    }
}

public partial class TimePicker : TimePicker<Microsoft.Maui.Controls.TimePicker>
{
    public TimePicker(Action<Microsoft.Maui.Controls.TimePicker?>? componentRefAction = null) : base(componentRefAction)
    {
    }

    public TimePicker(params IEnumerable<VisualNode?>? children)
    {
        if (children != null)
        {
            this.AddChildren(children);
        }
    }
}

public static partial class TimePickerExtensions
{
    public static T Format<T>(this T timePicker, string format)
        where T : ITimePicker
    {
        //timePicker.Format = format;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FormatProperty, format);
        return timePicker;
    }

    public static T TimePickerFormat<T>(this T timePicker, string format)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FormatProperty, format);
        return timePicker;
    }

    public static T Format<T>(this T timePicker, Func<string> formatFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FormatProperty, new PropertyValue<string>(formatFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerFormat<T>(this T timePicker, Func<string> formatFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FormatProperty, new PropertyValue<string>(formatFunc, componentWithState));
        return timePicker;
    }

    public static T TextColor<T>(this T timePicker, Microsoft.Maui.Graphics.Color textColor)
        where T : ITimePicker
    {
        //timePicker.TextColor = textColor;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TextColorProperty, textColor);
        return timePicker;
    }

    public static T TimePickerTextColor<T>(this T timePicker, Microsoft.Maui.Graphics.Color textColor)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TextColorProperty, textColor);
        return timePicker;
    }

    public static T TextColor<T>(this T timePicker, Func<Microsoft.Maui.Graphics.Color> textColorFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TextColorProperty, new PropertyValue<Microsoft.Maui.Graphics.Color>(textColorFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerTextColor<T>(this T timePicker, Func<Microsoft.Maui.Graphics.Color> textColorFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TextColorProperty, new PropertyValue<Microsoft.Maui.Graphics.Color>(textColorFunc, componentWithState));
        return timePicker;
    }

    public static T CharacterSpacing<T>(this T timePicker, double characterSpacing, RxDoubleAnimation? customAnimation = null)
        where T : ITimePicker
    {
        //timePicker.CharacterSpacing = characterSpacing;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.CharacterSpacingProperty, characterSpacing);
        timePicker.AppendAnimatable(Microsoft.Maui.Controls.TimePicker.CharacterSpacingProperty, customAnimation ?? new RxDoubleAnimation(characterSpacing));
        return timePicker;
    }

    public static T TimePickerCharacterSpacing<T>(this T timePicker, double characterSpacing, RxDoubleAnimation? customAnimation = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.CharacterSpacingProperty, characterSpacing);
        timePicker.AppendAnimatable(Microsoft.Maui.Controls.TimePicker.CharacterSpacingProperty, customAnimation ?? new RxDoubleAnimation(characterSpacing));
        return timePicker;
    }

    public static T CharacterSpacing<T>(this T timePicker, Func<double> characterSpacingFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.CharacterSpacingProperty, new PropertyValue<double>(characterSpacingFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerCharacterSpacing<T>(this T timePicker, Func<double> characterSpacingFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.CharacterSpacingProperty, new PropertyValue<double>(characterSpacingFunc, componentWithState));
        return timePicker;
    }

    public static T Time<T>(this T timePicker, System.Nullable<System.TimeSpan> time)
        where T : ITimePicker
    {
        //timePicker.Time = time;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TimeProperty, time);
        return timePicker;
    }

    public static T TimePickerTime<T>(this T timePicker, System.Nullable<System.TimeSpan> time)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TimeProperty, time);
        return timePicker;
    }

    public static T Time<T>(this T timePicker, Func<System.Nullable<System.TimeSpan>> timeFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TimeProperty, new PropertyValue<System.Nullable<System.TimeSpan>>(timeFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerTime<T>(this T timePicker, Func<System.Nullable<System.TimeSpan>> timeFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.TimeProperty, new PropertyValue<System.Nullable<System.TimeSpan>>(timeFunc, componentWithState));
        return timePicker;
    }

    public static T FontFamily<T>(this T timePicker, string fontFamily)
        where T : ITimePicker
    {
        //timePicker.FontFamily = fontFamily;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontFamilyProperty, fontFamily);
        return timePicker;
    }

    public static T TimePickerFontFamily<T>(this T timePicker, string fontFamily)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontFamilyProperty, fontFamily);
        return timePicker;
    }

    public static T FontFamily<T>(this T timePicker, Func<string> fontFamilyFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontFamilyProperty, new PropertyValue<string>(fontFamilyFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerFontFamily<T>(this T timePicker, Func<string> fontFamilyFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontFamilyProperty, new PropertyValue<string>(fontFamilyFunc, componentWithState));
        return timePicker;
    }

    public static T FontSize<T>(this T timePicker, double fontSize, RxDoubleAnimation? customAnimation = null)
        where T : ITimePicker
    {
        //timePicker.FontSize = fontSize;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontSizeProperty, fontSize);
        timePicker.AppendAnimatable(Microsoft.Maui.Controls.TimePicker.FontSizeProperty, customAnimation ?? new RxDoubleAnimation(fontSize));
        return timePicker;
    }

    public static T TimePickerFontSize<T>(this T timePicker, double fontSize, RxDoubleAnimation? customAnimation = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontSizeProperty, fontSize);
        timePicker.AppendAnimatable(Microsoft.Maui.Controls.TimePicker.FontSizeProperty, customAnimation ?? new RxDoubleAnimation(fontSize));
        return timePicker;
    }

    public static T FontSize<T>(this T timePicker, Func<double> fontSizeFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontSizeProperty, new PropertyValue<double>(fontSizeFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerFontSize<T>(this T timePicker, Func<double> fontSizeFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontSizeProperty, new PropertyValue<double>(fontSizeFunc, componentWithState));
        return timePicker;
    }

    public static T FontAttributes<T>(this T timePicker, Microsoft.Maui.Controls.FontAttributes fontAttributes)
        where T : ITimePicker
    {
        //timePicker.FontAttributes = fontAttributes;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAttributesProperty, fontAttributes);
        return timePicker;
    }

    public static T TimePickerFontAttributes<T>(this T timePicker, Microsoft.Maui.Controls.FontAttributes fontAttributes)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAttributesProperty, fontAttributes);
        return timePicker;
    }

    public static T FontAttributes<T>(this T timePicker, Func<Microsoft.Maui.Controls.FontAttributes> fontAttributesFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAttributesProperty, new PropertyValue<Microsoft.Maui.Controls.FontAttributes>(fontAttributesFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerFontAttributes<T>(this T timePicker, Func<Microsoft.Maui.Controls.FontAttributes> fontAttributesFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAttributesProperty, new PropertyValue<Microsoft.Maui.Controls.FontAttributes>(fontAttributesFunc, componentWithState));
        return timePicker;
    }

    public static T FontAutoScalingEnabled<T>(this T timePicker, bool fontAutoScalingEnabled)
        where T : ITimePicker
    {
        //timePicker.FontAutoScalingEnabled = fontAutoScalingEnabled;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAutoScalingEnabledProperty, fontAutoScalingEnabled);
        return timePicker;
    }

    public static T TimePickerFontAutoScalingEnabled<T>(this T timePicker, bool fontAutoScalingEnabled)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAutoScalingEnabledProperty, fontAutoScalingEnabled);
        return timePicker;
    }

    public static T FontAutoScalingEnabled<T>(this T timePicker, Func<bool> fontAutoScalingEnabledFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAutoScalingEnabledProperty, new PropertyValue<bool>(fontAutoScalingEnabledFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerFontAutoScalingEnabled<T>(this T timePicker, Func<bool> fontAutoScalingEnabledFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.FontAutoScalingEnabledProperty, new PropertyValue<bool>(fontAutoScalingEnabledFunc, componentWithState));
        return timePicker;
    }

    public static T IsOpen<T>(this T timePicker, bool isOpen)
        where T : ITimePicker
    {
        //timePicker.IsOpen = isOpen;
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.IsOpenProperty, isOpen);
        return timePicker;
    }

    public static T TimePickerIsOpen<T>(this T timePicker, bool isOpen)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.IsOpenProperty, isOpen);
        return timePicker;
    }

    public static T IsOpen<T>(this T timePicker, Func<bool> isOpenFunc, IComponentWithState? componentWithState = null)
        where T : ITimePicker
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.IsOpenProperty, new PropertyValue<bool>(isOpenFunc, componentWithState));
        return timePicker;
    }

    public static T TimePickerIsOpen<T>(this T timePicker, Func<bool> isOpenFunc, IComponentWithState? componentWithState = null)
        where T : Component
    {
        timePicker.SetProperty(Microsoft.Maui.Controls.TimePicker.IsOpenProperty, new PropertyValue<bool>(isOpenFunc, componentWithState));
        return timePicker;
    }

    public static T OnTimeSelected<T>(this T timePicker, Action? timeSelectedAction)
        where T : ITimePicker
    {
        timePicker.TimeSelectedEvent = new SyncEventCommand<TimeChangedEventArgs>(execute: timeSelectedAction);
        return timePicker;
    }

    public static T OnTimeSelected<T>(this T timePicker, Action<TimeChangedEventArgs>? timeSelectedAction)
        where T : ITimePicker
    {
        timePicker.TimeSelectedEvent = new SyncEventCommand<TimeChangedEventArgs>(executeWithArgs: timeSelectedAction);
        return timePicker;
    }

    public static T OnTimeSelected<T>(this T timePicker, Action<object?, TimeChangedEventArgs>? timeSelectedAction)
        where T : ITimePicker
    {
        timePicker.TimeSelectedEvent = new SyncEventCommand<TimeChangedEventArgs>(executeWithFullArgs: timeSelectedAction);
        return timePicker;
    }

    public static T OnTimeSelected<T>(this T timePicker, Func<Task>? timeSelectedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.TimeSelectedEvent = new AsyncEventCommand<TimeChangedEventArgs>(execute: timeSelectedAction, runInBackground);
        return timePicker;
    }

    public static T OnTimeSelected<T>(this T timePicker, Func<TimeChangedEventArgs, Task>? timeSelectedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.TimeSelectedEvent = new AsyncEventCommand<TimeChangedEventArgs>(executeWithArgs: timeSelectedAction, runInBackground);
        return timePicker;
    }

    public static T OnTimeSelected<T>(this T timePicker, Func<object?, TimeChangedEventArgs, Task>? timeSelectedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.TimeSelectedEvent = new AsyncEventCommand<TimeChangedEventArgs>(executeWithFullArgs: timeSelectedAction, runInBackground);
        return timePicker;
    }

    public static T OnOpened<T>(this T timePicker, Action? openedAction)
        where T : ITimePicker
    {
        timePicker.OpenedEvent = new SyncEventCommand<TimePickerOpenedEventArgs>(execute: openedAction);
        return timePicker;
    }

    public static T OnOpened<T>(this T timePicker, Action<TimePickerOpenedEventArgs>? openedAction)
        where T : ITimePicker
    {
        timePicker.OpenedEvent = new SyncEventCommand<TimePickerOpenedEventArgs>(executeWithArgs: openedAction);
        return timePicker;
    }

    public static T OnOpened<T>(this T timePicker, Action<object?, TimePickerOpenedEventArgs>? openedAction)
        where T : ITimePicker
    {
        timePicker.OpenedEvent = new SyncEventCommand<TimePickerOpenedEventArgs>(executeWithFullArgs: openedAction);
        return timePicker;
    }

    public static T OnOpened<T>(this T timePicker, Func<Task>? openedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.OpenedEvent = new AsyncEventCommand<TimePickerOpenedEventArgs>(execute: openedAction, runInBackground);
        return timePicker;
    }

    public static T OnOpened<T>(this T timePicker, Func<TimePickerOpenedEventArgs, Task>? openedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.OpenedEvent = new AsyncEventCommand<TimePickerOpenedEventArgs>(executeWithArgs: openedAction, runInBackground);
        return timePicker;
    }

    public static T OnOpened<T>(this T timePicker, Func<object?, TimePickerOpenedEventArgs, Task>? openedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.OpenedEvent = new AsyncEventCommand<TimePickerOpenedEventArgs>(executeWithFullArgs: openedAction, runInBackground);
        return timePicker;
    }

    public static T OnClosed<T>(this T timePicker, Action? closedAction)
        where T : ITimePicker
    {
        timePicker.ClosedEvent = new SyncEventCommand<TimePickerClosedEventArgs>(execute: closedAction);
        return timePicker;
    }

    public static T OnClosed<T>(this T timePicker, Action<TimePickerClosedEventArgs>? closedAction)
        where T : ITimePicker
    {
        timePicker.ClosedEvent = new SyncEventCommand<TimePickerClosedEventArgs>(executeWithArgs: closedAction);
        return timePicker;
    }

    public static T OnClosed<T>(this T timePicker, Action<object?, TimePickerClosedEventArgs>? closedAction)
        where T : ITimePicker
    {
        timePicker.ClosedEvent = new SyncEventCommand<TimePickerClosedEventArgs>(executeWithFullArgs: closedAction);
        return timePicker;
    }

    public static T OnClosed<T>(this T timePicker, Func<Task>? closedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.ClosedEvent = new AsyncEventCommand<TimePickerClosedEventArgs>(execute: closedAction, runInBackground);
        return timePicker;
    }

    public static T OnClosed<T>(this T timePicker, Func<TimePickerClosedEventArgs, Task>? closedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.ClosedEvent = new AsyncEventCommand<TimePickerClosedEventArgs>(executeWithArgs: closedAction, runInBackground);
        return timePicker;
    }

    public static T OnClosed<T>(this T timePicker, Func<object?, TimePickerClosedEventArgs, Task>? closedAction, bool runInBackground = false)
        where T : ITimePicker
    {
        timePicker.ClosedEvent = new AsyncEventCommand<TimePickerClosedEventArgs>(executeWithFullArgs: closedAction, runInBackground);
        return timePicker;
    }
}

public static partial class TimePickerStyles
{
    public static Action<ITimePicker>? Default { get; set; }
    public static Dictionary<string, Action<ITimePicker>> Themes { get; } = [];
}